apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Assuming your application is running on port 3000 in the pod
  type: ClusterIP
