# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: hello-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: 'manual'  
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"

apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - name: hello
      image: ghcr.io/aldinkapetanovic/hello-hostname
      volumeMounts:
        - name: logs-volume
          mountPath: /logs
  volumes:
    - name: logs-volume
      persistentVolumeClaim:
        claimName: logs-pvc
