apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: hello
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: 'hostpath'
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: ghcr.io/aldinkapetanovic/hello-hostname:latest
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
